//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.09 at 02:18:54 PM MSD 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ki.ru/model/query")
package ru.ki.dao.support.model.query;
