/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/dao/support/OrderBy.p.vm.java
 */
package ru.ki.dao.support;

import org.apache.commons.lang3.Validate;

import javax.persistence.metamodel.SingularAttribute;
import java.io.Serializable;

/**
 */
public class OrderBy implements Serializable {
    private static final long serialVersionUID = 1L;
    private String columnOrProperty;
    private OrderByDirection direction = OrderByDirection.ASC;

    public OrderBy(String columnOrProperty, OrderByDirection direction) {
        Validate.notNull(columnOrProperty);
        Validate.notNull(direction);
        this.columnOrProperty = columnOrProperty;
        this.direction = direction;
    }

    public OrderBy(String columnOrProperty) {
        this(columnOrProperty, OrderByDirection.ASC);
    }

    public OrderBy(SingularAttribute<?, ? extends Serializable> attribute, OrderByDirection direction) {
        Validate.notNull(attribute);
        Validate.notNull(direction);
        this.columnOrProperty = attribute.getName();
        this.direction = direction;
    }

    public OrderBy(SingularAttribute<?, ? extends Serializable> attribute) {
        this(attribute, OrderByDirection.ASC);
    }

    public String getColumn() {
        return columnOrProperty;
    }

    public String getProperty() {
        return columnOrProperty;
    }

    public OrderByDirection getDirection() {
        return direction;
    }

    public boolean isOrderDesc() {
        return OrderByDirection.DESC == direction;
    }
}