/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/dao/support/OrderBy.p.vm.java
 */
package ru.ki.dao.support;

import org.apache.commons.lang3.Validate;

import javax.persistence.metamodel.SingularAttribute;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import java.io.Serializable;

/**
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class OrderBy implements Serializable {
    private static final long serialVersionUID = 1L;
    private String fieldName;
    private OrderByDirection direction = OrderByDirection.ASC;

    public OrderBy() {
    }

    public OrderBy(String fieldName, OrderByDirection direction) {
        Validate.notNull(fieldName);
        Validate.notNull(direction);
        this.fieldName = fieldName;
        this.direction = direction;
    }

    public OrderBy(String fieldName) {
        this(fieldName, OrderByDirection.ASC);
    }

    public String getFieldName() {
        return fieldName;
    }

    public OrderByDirection getDirection() {
        return direction;
    }

    public boolean isOrderDesc() {
        return OrderByDirection.DESC == direction;
    }
}