//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.09 at 02:18:54 PM MSD 
//


package ru.ki.model.query;

import ru.ki.dao.support.*;

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class ObjectFactory {

    public ObjectFactory() {
    }

    public ValueType createValueType() {
        return new ValueType();
    }

    public SearchParameters createSearchParameters() {
        return new SearchParameters();
    }

    public FilterElement createFilterElement() {
        return new FilterElement();
    }

    public QueryDescriptor createQueryDescriptor() {
        return new QueryDescriptor();
    }

    public SelectElement createSelectElement() {
        return new SelectElement();
    }

}
